interface=wlan1
ssid=WEPTest
hw_mode=g
channel=6
auth_algs=1
macaddr_acl=1
accept_mac_file=/etc/hostapd/accept_mac
ignore_broadcast_ssid=1
wep_default_key=0
wep_key0=AABBCCDDEEFFAABBCCDDEEFF00
wep_key1=112233445566778899AABBCCDD
wep_key2=FFEEDDCCBBAA998877665544FF
wep_key3=0102030405060708090A0B0C0D
eapol_key_index_workaround=1
ap_max_inactivity=300
rts_threshold=2347
fragm_threshold=2346
