interface=wlan1
ssid=WPSTest
hw_mode=g
channel=6
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=TestPassword1
eap_server=1
wps_state=2
ap_pin=12345670
device_type=6-0050F204-1
config_methods=keypad
